language: node_js
cache:
  npm: true
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
script:
  - npm test
  - npm run lint
  - 'npm run lint:commit'
after_success:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
